package com.dozor.serverinteraction.bean;

/**
 * @author IGOR-K
 */
public enum Errors {
    ERROR_PLAYER_INDEX_DOES_NOT_EXISTS,
    ERROR_INCORRECT_PLAYER_INDEX_WHILE_CALC_TRIBUNAL_POINTS,
    ERROR_INCORRECT_TIME_FOR_TRIBUNAL_POINTS,
    ERROR_INCORRECT_PART_OF_TURN,
    ERROR_LITTLE_MANA,
    ERROR_UP_MP_NOT_ON_ZERO_FLOOR,
    ERROR_FLOOR_IS_ZERO,
    ERROR_INCORRECT_UNIT_INDEX,
    ERROR_UNIT_INVISIBLE_BECAUSE_LEVEL,
    ERROR_FEW_EVIDENCES,
    ERROR_TRIBUNAL_NEED_POINTS_LIST,
    ERROR_TRIBUNAL_NOT_ALL_POINTS_LIST,
    ERROR_TRIBUNAL_POINT_LESS_THAN_ZERO,
    ERROR_TRIBUNAL_POINT_INCORRECT_SUM,
    ERROR_INCORRECT_ACTION_TYPE;
}
