package com.dozor.ui;

import com.dozor.config.AppConfig;
import com.dozor.langs.LocaleBundle;
import com.dozorengine.serverinteraction.StringSocketClient;
import com.dozorengine.serverinteraction.bean.CreateSessionBean;
import com.dozorengine.serverinteraction.bean.JoinSessionBean;
import com.dozor.serverinteraction.parsers.CreateSessionBeanToParser;
import com.dozor.serverinteraction.parsers.JoinSessionBeanToParser;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author IGOR-K
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
        jTextFieldLogin.setText(UUID.randomUUID().toString());

        jButtonCreateSession.setText(LocaleBundle.getInstance().getString("create"));
        jButtonJoinSession.setText(LocaleBundle.getInstance().getString("join"));
        jLabelLogin.setText(LocaleBundle.getInstance().getString("login_"));
        jLabelNick.setText(LocaleBundle.getInstance().getString("nick_"));
        jLabelPC.setText(LocaleBundle.getInstance().getString("player_count_"));
        jLabelPort.setText(LocaleBundle.getInstance().getString("port_"));
        jLabelSesId.setText(LocaleBundle.getInstance().getString("session_number_"));
        jLabelSrvr.setText(LocaleBundle.getInstance().getString("server_"));
    }

    private StringSocketClient cs;
    private Callback callback;

    private boolean checkNick() {
        if (jTextFieldNick.getText() == null || jTextFieldNick.getText().trim().isEmpty()) {
            Dialogs.showErrDialog(this,
                    LocaleBundle.getInstance().getString("no_nick"),
                    LocaleBundle.getInstance().getString("client_error"));
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogin = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabelNick = new javax.swing.JLabel();
        jTextFieldNick = new javax.swing.JTextField();
        jLabelSesId = new javax.swing.JLabel();
        jTextSessionId = new javax.swing.JTextField();
        jButtonCreateSession = new javax.swing.JButton();
        jLabelPC = new javax.swing.JLabel();
        jTextPlayerCount = new javax.swing.JTextField();
        jLabelSrvr = new javax.swing.JLabel();
        jTextHost = new javax.swing.JTextField();
        jLabelPort = new javax.swing.JLabel();
        jTextPort = new javax.swing.JTextField();
        jButtonJoinSession = new javax.swing.JButton();

        jLabelLogin.setText("Login");

        jLabelNick.setText("Nick");

        jLabelSesId.setText("Session ID");

        jTextSessionId.setText("0");

        jButtonCreateSession.setText("Create");
        jButtonCreateSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateSessionActionPerformed(evt);
            }
        });

        jLabelPC.setText("Player Count");

        jTextPlayerCount.setText("2");
        jTextPlayerCount.setEnabled(false);

        jLabelSrvr.setText("Srever");

        jTextHost.setText("46.0.15.47");

        jLabelPort.setText("Port");

        jTextPort.setText("30303");

        jButtonJoinSession.setText("Join");
        jButtonJoinSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJoinSessionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSrvr)
                            .addComponent(jLabelPort))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextPort)
                            .addComponent(jTextHost, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNick)
                            .addComponent(jLabelPC)
                            .addComponent(jLabelLogin))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldLogin)
                                    .addComponent(jTextFieldNick)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextPlayerCount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelSesId))
                                    .addComponent(jButtonCreateSession))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonJoinSession)
                                    .addComponent(jTextSessionId, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSrvr)
                    .addComponent(jTextHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPort)
                    .addComponent(jTextPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogin)
                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNick)
                    .addComponent(jTextFieldNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSesId)
                    .addComponent(jTextSessionId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPC)
                    .addComponent(jTextPlayerCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCreateSession)
                    .addComponent(jButtonJoinSession))
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateSessionActionPerformed
        if (!checkNick()) {
            return;
        }
        CreateSessionBean csb = new CreateSessionBean();
        csb.setLogin(jTextFieldLogin.getText());
        csb.setNick(jTextFieldNick.getText());
        csb.setMaxPlayers(Integer.valueOf(jTextPlayerCount.getText()));

        try {
            cs = new StringSocketClient(jTextHost.getText(), Integer.valueOf(jTextPort.getText()));
            cs.setLogging(AppConfig.DEBUG_JSONS);
            cs.init();
            String data = CreateSessionBeanToParser.toJson(csb).toString();

            cs.sendString(data);
        } catch (Exception ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
            cs.closeAll();
            System.exit(-1);
        }

        callback.onSocketFirstDataSent(cs);

    }//GEN-LAST:event_jButtonCreateSessionActionPerformed

    private void jButtonJoinSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJoinSessionActionPerformed
        if (!checkNick()) {
            return;
        }
        JoinSessionBean jsb = new JoinSessionBean();
        jsb.setLogin(jTextFieldLogin.getText());
        jsb.setNick(jTextFieldNick.getText());
        jsb.setSessionNumber(Integer.valueOf(jTextSessionId.getText()));

        try {
            cs = new StringSocketClient(jTextHost.getText(), Integer.valueOf(jTextPort.getText()));
            cs.setLogging(AppConfig.DEBUG_JSONS);
            cs.init();
            String data = JoinSessionBeanToParser.toJson(jsb).toString();

            cs.sendString(data);
        } catch (Exception ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
            cs.closeAll();
            System.exit(-1);
        }

        callback.onSocketFirstDataSent(cs);

    }//GEN-LAST:event_jButtonJoinSessionActionPerformed

    public static interface Callback {

        void onSocketFirstDataSent(StringSocketClient socket);
    }

    public void setCallback(Callback callback) {
        this.callback = callback;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateSession;
    private javax.swing.JButton jButtonJoinSession;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelNick;
    private javax.swing.JLabel jLabelPC;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JLabel jLabelSesId;
    private javax.swing.JLabel jLabelSrvr;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldNick;
    private javax.swing.JTextField jTextHost;
    private javax.swing.JTextField jTextPlayerCount;
    private javax.swing.JTextField jTextPort;
    private javax.swing.JTextField jTextSessionId;
    // End of variables declaration//GEN-END:variables
}
