package com.dozor.ui.game;

import com.dozor.game.beans.GameState;
import com.dozor.game.beans.GameUtils;
import com.dozor.game.beans.Unit;
import com.dozor.game.utils.LevelCalculator;
import com.dozor.langs.LocaleBundle;
import com.dozor.ui.colors.Colors;
import com.dozor.ui.send.GameEventsSender;
import java.awt.Color;

/**
 *
 * @author IGOR-K
 */
public class UnitJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UnitJPanel
     */
    public UnitJPanel() {
        initComponents();
        jLabelHp.setText(LocaleBundle.getInstance().getString("unit_hp"));
        jLabelMp.setText(LocaleBundle.getInstance().getString("unit_mp"));
        jLabelXp.setText(LocaleBundle.getInstance().getString("unit_xp"));
        jLabelStage.setText(LocaleBundle.getInstance().getString("stage"));
        jLabelTBPoints.setText(LocaleBundle.getInstance().getString("tribunal_points"));
    }

    private boolean fireable;
    private boolean tribunalable;
    private int unitIndex;

    private Unit u;
    private GameState gameState;

    public void setUnit(GameState gameState, int playerIndex, int unitIndex) {
        fireable = false;
        tribunalable = false;
        this.gameState = gameState;
        this.unitIndex = unitIndex;
        u = gameState.getPlayers().get(playerIndex).getUnitsList().get(unitIndex);
        if (gameState.getTurnPosition().getPlayerIndex() == playerIndex && gameState.getTurnPosition().getUnitIndex() == unitIndex) {
            this.setBackground(Colors.getInstance().getCurrentUnitColor());
        } else {
            this.setBackground(Colors.getInstance().getNormalUnitColor());
        }
        jLabelHpText.setText("" + u.getHp());
        jLabelMpText.setText("" + u.getMp());
        jLabelXpText.setText("" + u.getXp());
        jLabelStageText.setText("" + u.getStage());
        jPanelLevelColor1.setLevelAndColor(LevelCalculator.getLevelByExp(u.getXp()), playerIndex == 0 ? Color.WHITE : Color.BLACK);
        jFormattedTextFieldTBPoints.setText(u.getTribunalPoints() == null ? "" : u.getTribunalPoints().toString());
    }

    public void setFireable(int stage) {
        this.fireable = u.getStage() <= stage;
        updateColor();
    }

    public void setTribunalable() {
        int evidences = GameUtils.getCurrentPlayer(gameState).getEvidences();
        if (u.getTribunalPoints().compareTo(evidences) <= 0) {
            tribunalable = true;
        }
        updateColor();
    }

    private void updateColor() {
        if (fireable || tribunalable) {
            this.setBackground(Colors.getInstance().getUnitForKillColor());
        } else {
            this.setBackground(Colors.getInstance().getNormalUnitColor());
        }
    }

    public Integer getPoints() {
        return Integer.parseInt(jFormattedTextFieldTBPoints.getText());
    }

    public int getUnitIndex() {
        return unitIndex;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLevelColor1 = new com.dozor.ui.game.JPanelLevel();
        jLabelHp = new javax.swing.JLabel();
        jLabelMp = new javax.swing.JLabel();
        jLabelXp = new javax.swing.JLabel();
        jLabelHpText = new javax.swing.JLabel();
        jLabelMpText = new javax.swing.JLabel();
        jLabelXpText = new javax.swing.JLabel();
        jLabelStage = new javax.swing.JLabel();
        jLabelStageText = new javax.swing.JLabel();
        jLabelTBPoints = new javax.swing.JLabel();
        jFormattedTextFieldTBPoints = new javax.swing.JFormattedTextField();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(280, 32767));
        setMinimumSize(new java.awt.Dimension(140, 0));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelLevelColor1Layout = new javax.swing.GroupLayout(jPanelLevelColor1);
        jPanelLevelColor1.setLayout(jPanelLevelColor1Layout);
        jPanelLevelColor1Layout.setHorizontalGroup(
            jPanelLevelColor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelLevelColor1Layout.setVerticalGroup(
            jPanelLevelColor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        jLabelHp.setText("jLabel1");

        jLabelMp.setText("jLabel2");

        jLabelXp.setText("jLabel3");

        jLabelHpText.setText("jLabel4");

        jLabelMpText.setText("jLabel5");

        jLabelXpText.setText("jLabel6");

        jLabelStage.setText("jLabel3");

        jLabelStageText.setText("jLabel6");

        jLabelTBPoints.setText("Очки трибунала");

        jFormattedTextFieldTBPoints.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHp)
                            .addComponent(jLabelMp)
                            .addComponent(jLabelXp)
                            .addComponent(jLabelStage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelXpText)
                            .addComponent(jLabelMpText)
                            .addComponent(jLabelHpText)
                            .addComponent(jLabelStageText))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelLevelColor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTBPoints)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldTBPoints, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelLevelColor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTBPoints)
                    .addComponent(jFormattedTextFieldTBPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHp)
                    .addComponent(jLabelHpText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMp)
                    .addComponent(jLabelMpText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelXp)
                    .addComponent(jLabelXpText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStageText)
                    .addComponent(jLabelStage))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (tribunalable) {
            GameEventsSender.getInstance().sendTribunalKill(unitIndex);
        } else if (fireable) {
            GameEventsSender.getInstance().fire(unitIndex);
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextFieldTBPoints;
    private javax.swing.JLabel jLabelHp;
    private javax.swing.JLabel jLabelHpText;
    private javax.swing.JLabel jLabelMp;
    private javax.swing.JLabel jLabelMpText;
    private javax.swing.JLabel jLabelStage;
    private javax.swing.JLabel jLabelStageText;
    private javax.swing.JLabel jLabelTBPoints;
    private javax.swing.JLabel jLabelXp;
    private javax.swing.JLabel jLabelXpText;
    private com.dozor.ui.game.JPanelLevel jPanelLevelColor1;
    // End of variables declaration//GEN-END:variables
}
