package com.dozor.ui.game;

import com.dozor.langs.LocaleBundle;
import com.dozor.ui.send.GameEventsSender;

/**
 *
 * @author IGOR-K
 */
public class UpDownJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpDownJPanel
     */
    public UpDownJPanel() {
        initComponents();
        jButtonDown.setText(LocaleBundle.getInstance().getString("buttonDown"));
        jButtonUp.setText(LocaleBundle.getInstance().getString("buttonUp"));
        jLabelParam.setText(LocaleBundle.getInstance().getString("layer"));
    }

    @Override
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled); //To change body of generated methods, choose Tools | Templates.
        jButtonDown.setEnabled(enabled);
        jButtonUp.setEnabled(enabled);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDown = new javax.swing.JButton();
        jLabelParam = new javax.swing.JLabel();
        jButtonUp = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        jButtonDown.setText("Глубже");
        jButtonDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownActionPerformed(evt);
            }
        });
        add(jButtonDown);

        jLabelParam.setText("слой");
        add(jLabelParam);

        jButtonUp.setText("Наружу");
        jButtonUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpActionPerformed(evt);
            }
        });
        add(jButtonUp);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownActionPerformed
        GameEventsSender.getInstance().downStage();
    }//GEN-LAST:event_jButtonDownActionPerformed

    private void jButtonUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpActionPerformed
        GameEventsSender.getInstance().upStage();
    }//GEN-LAST:event_jButtonUpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDown;
    private javax.swing.JButton jButtonUp;
    private javax.swing.JLabel jLabelParam;
    // End of variables declaration//GEN-END:variables
}
